# Generated by Django 2.2.28 on 2022-07-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220721_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sda',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
