# Generated by Django 2.2.28 on 2022-07-21 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_sda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sda',
        ),
    ]
