# Generated by Django 2.2.28 on 2022-07-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_sda'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ffff',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
