# Generated by Django 2.2.28 on 2022-07-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_ffff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fffsssaa',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
