# Generated by Django 2.2.28 on 2022-07-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_fffsssaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='khjkj',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
