# Generated by Django 2.2.28 on 2022-08-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_khjkj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='asd',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ffff',
        ),
    ]
