# Generated by Django 2.2.28 on 2022-08-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220801_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuuiiuuu',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
