# Generated by Django 2.2.28 on 2022-08-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_uuuiiuuu'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cderfv',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
