# Generated by Django 2.2.28 on 2022-08-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_cderfv'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vcxz',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
