# Generated by Django 2.2.28 on 2022-08-02 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_vcxz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cderfv',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fffsssaa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='khjkj',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uuuiiuuu',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vcxz',
        ),
    ]
