# Generated by Django 2.2.28 on 2022-08-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220802_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='asd',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ffff',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fffsssaa',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
