# Generated by Django 2.2.28 on 2022-08-02 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220802_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='asd',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ffff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fffsssaa',
        ),
    ]
