# Generated by Django 2.2.28 on 2022-08-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220802_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fdsafasd',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
