# Generated by Django 2.2.28 on 2022-08-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_fdsafasd'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xxxx',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
