# Generated by Django 2.2.28 on 2022-08-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_xxxx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fdsafasd',
            new_name='asd',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='xxxx',
            new_name='ffff',
        ),
        migrations.AddField(
            model_name='user',
            name='fffsssaa',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
