# Generated by Django 2.2.28 on 2022-08-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20220809_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oooppoo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
