# Generated by Django 2.2.28 on 2022-08-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_oooppoo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aapppaaa',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
